version: "3.7"
services:
  app:
    build:      
      context: ./
      dockerfile: Dockerfile
    image: lara-api
    container_name: lara-api-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - lara-api
  
  db:
    image: mariadb:10.4
    container_name: lara-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_api
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"     
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
      - ./docker-compose/mysql/drugvisi_api.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - lara-api
  
  nginx:
    image: nginx:alpine
    container_name: lara-api-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lara-api

networks:
  lara-api:
    name: lara-api
    